-- ARKORA V1 — 002_seed.sql
-- Généré depuis data/ids.json (95 works, 117 seasons). Ne pas éditer à la main :
-- régénérer avec gen_seed_sql.py si ids.json change (ids sont gelés après ce lot).

insert into work (id, universe_id, title, kind, year, synopsis, is_released, is_target_event, chrono_order) values
  ('mcu-les-eternels', 'mcu', 'Les Éternels', 'film', null, null, true, false, null),
  ('mcu-captain-america-first-avenger', 'mcu', 'Captain America : First Avenger', 'film', null, null, true, false, null),
  ('tv-agent-carter', 'mcu', 'Agent Carter', 'series', null, null, true, false, null),
  ('mcu-captain-marvel', 'mcu', 'Captain Marvel', 'film', null, null, true, false, null),
  ('mcu-iron-man', 'mcu', 'Iron Man', 'film', null, null, true, false, null),
  ('mcu-l-incroyable-hulk', 'mcu', 'L''Incroyable Hulk', 'film', null, null, true, false, null),
  ('mcu-iron-man-2', 'mcu', 'Iron Man 2', 'film', null, null, true, false, null),
  ('mcu-thor', 'mcu', 'Thor', 'film', null, null, true, false, null),
  ('mcu-avengers', 'mcu', 'Avengers', 'film', null, null, true, false, null),
  ('mcu-iron-man-3', 'mcu', 'Iron Man 3', 'film', null, null, true, false, null),
  ('mcu-thor-le-monde-des-tenebres', 'mcu', 'Thor : Le Monde des Ténèbres', 'film', null, null, true, false, null),
  ('mcu-captain-america-le-soldat-de-l-hiver', 'mcu', 'Captain America : Le Soldat de l''Hiver', 'film', null, null, true, false, null),
  ('mcu-les-gardiens-de-la-galaxie', 'mcu', 'Les Gardiens de la Galaxie', 'film', null, null, true, false, null),
  ('mcu-avengers-l-ere-d-ultron', 'mcu', 'Avengers : L''Ère d''Ultron', 'film', null, null, true, false, null),
  ('mcu-ant-man', 'mcu', 'Ant-Man', 'film', null, null, true, false, null),
  ('mcu-captain-america-civil-war', 'mcu', 'Captain America : Civil War', 'film', null, null, true, false, null),
  ('mcu-doctor-strange', 'mcu', 'Doctor Strange', 'film', null, null, true, false, null),
  ('mcu-les-gardiens-de-la-galaxie-vol-2', 'mcu', 'Les Gardiens de la Galaxie Vol. 2', 'film', null, null, true, false, null),
  ('mcu-spider-man-homecoming', 'mcu', 'Spider-Man : Homecoming', 'film', null, null, true, false, null),
  ('mcu-thor-ragnarok', 'mcu', 'Thor : Ragnarok', 'film', null, null, true, false, null),
  ('mcu-black-panther', 'mcu', 'Black Panther', 'film', null, null, true, false, null),
  ('mcu-avengers-infinity-war', 'mcu', 'Avengers : Infinity War', 'film', null, null, true, false, null),
  ('mcu-ant-man-et-la-guepe', 'mcu', 'Ant-Man et la Guêpe', 'film', null, null, true, false, null),
  ('mcu-avengers-endgame', 'mcu', 'Avengers : Endgame', 'film', null, null, true, false, null),
  ('mcu-spider-man-far-from-home', 'mcu', 'Spider-Man : Far From Home', 'film', null, null, true, false, null),
  ('mcu-black-widow', 'mcu', 'Black Widow', 'film', null, null, true, false, null),
  ('mcu-wandavision', 'mcu', 'WandaVision', 'series', null, null, true, false, null),
  ('mcu-falcon-et-le-soldat-de-l-hiver', 'mcu', 'Falcon et le Soldat de l''Hiver', 'series', null, null, true, false, null),
  ('mcu-loki', 'mcu', 'Loki', 'series', null, null, true, false, null),
  ('mcu-what-if', 'mcu', 'What If...?', 'series', null, null, true, false, null),
  ('mcu-hawkeye', 'mcu', 'Hawkeye', 'series', null, null, true, false, null),
  ('mcu-moon-knight', 'mcu', 'Moon Knight', 'series', null, null, true, false, null),
  ('mcu-ms-marvel', 'mcu', 'Ms. Marvel', 'series', null, null, true, false, null),
  ('mcu-i-am-groot', 'mcu', 'I Am Groot', 'series', null, null, true, false, null),
  ('mcu-she-hulk-avocate', 'mcu', 'She-Hulk : Avocate', 'series', null, null, true, false, null),
  ('mcu-werewolf-by-night', 'mcu', 'Werewolf by Night', 'special', null, null, true, false, null),
  ('mcu-les-gardiens-special-fetes', 'mcu', 'Les Gardiens : Spécial Fêtes', 'special', null, null, true, false, null),
  ('mcu-shang-chi-et-la-legende-des-dix-anneaux', 'mcu', 'Shang-Chi et la Légende des Dix Anneaux', 'film', null, null, true, false, null),
  ('mcu-spider-man-no-way-home', 'mcu', 'Spider-Man : No Way Home', 'film', null, null, true, false, null),
  ('mcu-doctor-strange-multiverse-of-madness', 'mcu', 'Doctor Strange : Multiverse of Madness', 'film', null, null, true, false, null),
  ('mcu-thor-love-and-thunder', 'mcu', 'Thor : Love and Thunder', 'film', null, null, true, false, null),
  ('mcu-black-panther-wakanda-forever', 'mcu', 'Black Panther : Wakanda Forever', 'film', null, null, true, false, null),
  ('mcu-secret-invasion', 'mcu', 'Secret Invasion', 'series', null, null, true, false, null),
  ('mcu-ant-man-et-la-guepe-quantumania', 'mcu', 'Ant-Man et la Guêpe : Quantumania', 'film', null, null, true, false, null),
  ('mcu-les-gardiens-de-la-galaxie-vol-3', 'mcu', 'Les Gardiens de la Galaxie Vol. 3', 'film', null, null, true, false, null),
  ('mcu-the-marvels', 'mcu', 'The Marvels', 'film', null, null, true, false, null),
  ('mcu-echo', 'mcu', 'Echo', 'series', null, null, true, false, null),
  ('fox-x-men-97', 'mcu', 'X-Men ''97', 'series', null, null, true, false, null),
  ('mcu-agatha-all-along', 'mcu', 'Agatha All Along', 'series', null, null, true, false, null),
  ('mcu-your-friendly-neighborhood-spider-man', 'mcu', 'Your Friendly Neighborhood Spider-Man', 'series', null, null, true, false, null),
  ('fox-deadpool-wolverine', 'mcu', 'Deadpool & Wolverine', 'film', null, null, true, false, null),
  ('tv-daredevil-born-again', 'mcu', 'Daredevil : Born Again', 'series', null, null, true, false, null),
  ('mcu-ironheart', 'mcu', 'Ironheart', 'series', null, null, true, false, null),
  ('mcu-marvel-zombies', 'mcu', 'Marvel Zombies', 'series', null, null, true, false, null),
  ('mcu-captain-america-brave-new-world', 'mcu', 'Captain America : Brave New World', 'film', null, null, true, false, null),
  ('mcu-thunderbolts', 'mcu', 'Thunderbolts*', 'film', null, null, true, false, null),
  ('f4-les-4-fantastiques-premiers-pas', 'mcu', 'Les 4 Fantastiques : Premiers Pas', 'film', null, null, true, false, null),
  ('mcu-eyes-of-wakanda', 'mcu', 'Eyes of Wakanda', 'series', null, null, true, false, null),
  ('mcu-wonder-man', 'mcu', 'Wonder Man', 'series', null, null, true, false, null),
  ('mcu-visionquest', 'mcu', 'VisionQuest', 'series', null, null, false, false, null),
  ('mcu-spider-man-brand-new-day', 'mcu', 'Spider-Man : Brand New Day', 'film', null, null, true, false, null),
  ('mcu-avengers-doomsday', 'mcu', 'AVENGERS : DOOMSDAY', 'film', null, null, false, true, null),
  ('tv-daredevil', 'mcu', 'Daredevil', 'series', null, null, true, false, null),
  ('tv-jessica-jones', 'mcu', 'Jessica Jones', 'series', null, null, true, false, null),
  ('tv-luke-cage', 'mcu', 'Luke Cage', 'series', null, null, true, false, null),
  ('tv-iron-fist', 'mcu', 'Iron Fist', 'series', null, null, true, false, null),
  ('tv-the-defenders', 'mcu', 'The Defenders', 'series', null, null, true, false, null),
  ('tv-the-punisher', 'mcu', 'The Punisher', 'series', null, null, true, false, null),
  ('tv-agents-of-s-h-i-e-l-d', 'mcu', 'Agents of S.H.I.E.L.D.', 'series', null, null, true, false, null),
  ('tv-inhumans', 'mcu', 'Inhumans', 'series', null, null, true, false, null),
  ('tv-runaways', 'mcu', 'Runaways', 'series', null, null, true, false, null),
  ('tv-cloak-dagger', 'mcu', 'Cloak & Dagger', 'series', null, null, true, false, null),
  ('tv-helstrom', 'mcu', 'Helstrom', 'series', null, null, true, false, null),
  ('mcu-the-consultant', 'mcu', 'The Consultant', 'oneshot', null, null, true, false, null),
  ('mcu-a-funny-thing-happened-on-the-way-to-thor-s-', 'mcu', 'A Funny Thing Happened on the Way to Thor''s Hammer', 'oneshot', null, null, true, false, null),
  ('mcu-item-47', 'mcu', 'Item 47', 'oneshot', null, null, true, false, null),
  ('tv-agent-carter-one-shot', 'mcu', 'Agent Carter (One-Shot)', 'oneshot', null, null, true, false, null),
  ('mcu-all-hail-the-king', 'mcu', 'All Hail the King', 'oneshot', null, null, true, false, null),
  ('fox-x-men', 'mcu', 'X-Men', 'film', null, null, true, false, null),
  ('fox-x-men-2', 'mcu', 'X-Men 2', 'film', null, null, true, false, null),
  ('fox-x-men-l-affrontement-final', 'mcu', 'X-Men : L''Affrontement final', 'film', null, null, true, false, null),
  ('fox-x-men-days-of-future-past', 'mcu', 'X-Men : Days of Future Past', 'film', null, null, true, false, null),
  ('fox-logan', 'mcu', 'Logan', 'film', null, null, true, false, null),
  ('fox-deadpool', 'mcu', 'Deadpool', 'film', null, null, true, false, null),
  ('fox-deadpool-2', 'mcu', 'Deadpool 2', 'film', null, null, true, false, null),
  ('fox-x-men-le-commencement', 'mcu', 'X-Men : Le Commencement', 'film', null, null, true, false, null),
  ('fox-x-men-apocalypse', 'mcu', 'X-Men : Apocalypse', 'film', null, null, true, false, null),
  ('fox-dark-phoenix', 'mcu', 'Dark Phoenix', 'film', null, null, true, false, null),
  ('fox-wolverine-le-combat-de-l-immortel', 'mcu', 'Wolverine : Le Combat de l''immortel', 'film', null, null, true, false, null),
  ('fox-x-men-origins-wolverine', 'mcu', 'X-Men Origins : Wolverine', 'film', null, null, true, false, null),
  ('raimi-spider-man', 'mcu', 'Spider-Man', 'film', null, null, true, false, null),
  ('raimi-spider-man-2', 'mcu', 'Spider-Man 2', 'film', null, null, true, false, null),
  ('raimi-spider-man-3', 'mcu', 'Spider-Man 3', 'film', null, null, true, false, null),
  ('webb-the-amazing-spider-man', 'mcu', 'The Amazing Spider-Man', 'film', null, null, true, false, null),
  ('webb-the-amazing-spider-man-2', 'mcu', 'The Amazing Spider-Man 2', 'film', null, null, true, false, null);

insert into season (id, work_id, number, title, episodes, runtime_min, runtime_is_estimate, narrative_weight, chrono_order) values
  ('mcu-les-eternels-s0', 'mcu-les-eternels', 0, null, null, null, true, null, null),
  ('mcu-captain-america-first-avenger-s0', 'mcu-captain-america-first-avenger', 0, null, null, null, true, null, null),
  ('tv-agent-carter-s1', 'tv-agent-carter', 1, null, null, null, true, null, null),
  ('tv-agent-carter-s2', 'tv-agent-carter', 2, null, null, null, true, null, null),
  ('mcu-captain-marvel-s0', 'mcu-captain-marvel', 0, null, null, null, true, null, null),
  ('mcu-iron-man-s0', 'mcu-iron-man', 0, null, null, 126, false, 96, 1),
  ('mcu-l-incroyable-hulk-s0', 'mcu-l-incroyable-hulk', 0, null, null, null, true, null, null),
  ('mcu-iron-man-2-s0', 'mcu-iron-man-2', 0, null, null, null, true, null, null),
  ('mcu-thor-s0', 'mcu-thor', 0, null, null, null, true, null, null),
  ('mcu-avengers-s0', 'mcu-avengers', 0, null, null, 143, false, 88, 2),
  ('mcu-iron-man-3-s0', 'mcu-iron-man-3', 0, null, null, null, true, null, null),
  ('mcu-thor-le-monde-des-tenebres-s0', 'mcu-thor-le-monde-des-tenebres', 0, null, null, null, true, null, null),
  ('mcu-captain-america-le-soldat-de-l-hiver-s0', 'mcu-captain-america-le-soldat-de-l-hiver', 0, null, null, null, true, null, null),
  ('mcu-les-gardiens-de-la-galaxie-s0', 'mcu-les-gardiens-de-la-galaxie', 0, null, null, null, true, null, null),
  ('mcu-avengers-l-ere-d-ultron-s0', 'mcu-avengers-l-ere-d-ultron', 0, null, null, null, true, null, null),
  ('mcu-ant-man-s0', 'mcu-ant-man', 0, null, null, null, true, null, null),
  ('mcu-captain-america-civil-war-s0', 'mcu-captain-america-civil-war', 0, null, null, 147, false, 90, 3),
  ('mcu-doctor-strange-s0', 'mcu-doctor-strange', 0, null, null, null, true, null, null),
  ('mcu-les-gardiens-de-la-galaxie-vol-2-s0', 'mcu-les-gardiens-de-la-galaxie-vol-2', 0, null, null, null, true, null, null),
  ('mcu-spider-man-homecoming-s0', 'mcu-spider-man-homecoming', 0, null, null, 133, false, 84, 4),
  ('mcu-thor-ragnarok-s0', 'mcu-thor-ragnarok', 0, null, null, null, true, null, null),
  ('mcu-black-panther-s0', 'mcu-black-panther', 0, null, null, null, true, null, null),
  ('mcu-avengers-infinity-war-s0', 'mcu-avengers-infinity-war', 0, null, null, 149, false, 98, 5),
  ('mcu-ant-man-et-la-guepe-s0', 'mcu-ant-man-et-la-guepe', 0, null, null, null, true, null, null),
  ('mcu-avengers-endgame-s0', 'mcu-avengers-endgame', 0, null, null, 181, false, 99, 6),
  ('mcu-spider-man-far-from-home-s0', 'mcu-spider-man-far-from-home', 0, null, null, 129, false, 86, 7),
  ('mcu-black-widow-s0', 'mcu-black-widow', 0, null, null, null, true, null, null),
  ('mcu-wandavision-s1', 'mcu-wandavision', 1, null, null, null, true, null, null),
  ('mcu-falcon-et-le-soldat-de-l-hiver-s1', 'mcu-falcon-et-le-soldat-de-l-hiver', 1, null, null, null, true, null, null),
  ('mcu-loki-s1', 'mcu-loki', 1, null, null, 288, true, 94, 8),
  ('mcu-loki-s2', 'mcu-loki', 2, null, null, 300, true, 92, 11),
  ('mcu-what-if-s1', 'mcu-what-if', 1, null, null, null, true, null, null),
  ('mcu-what-if-s2', 'mcu-what-if', 2, null, null, null, true, null, null),
  ('mcu-what-if-s3', 'mcu-what-if', 3, null, null, null, true, null, null),
  ('mcu-hawkeye-s1', 'mcu-hawkeye', 1, null, null, null, true, null, null),
  ('mcu-moon-knight-s1', 'mcu-moon-knight', 1, null, null, null, true, null, null),
  ('mcu-ms-marvel-s1', 'mcu-ms-marvel', 1, null, null, null, true, null, null),
  ('mcu-i-am-groot-s1', 'mcu-i-am-groot', 1, null, null, null, true, null, null),
  ('mcu-i-am-groot-s2', 'mcu-i-am-groot', 2, null, null, null, true, null, null),
  ('mcu-she-hulk-avocate-s1', 'mcu-she-hulk-avocate', 1, null, null, null, true, null, null),
  ('mcu-werewolf-by-night-s0', 'mcu-werewolf-by-night', 0, null, null, null, true, null, null),
  ('mcu-les-gardiens-special-fetes-s0', 'mcu-les-gardiens-special-fetes', 0, null, null, null, true, null, null),
  ('mcu-shang-chi-et-la-legende-des-dix-anneaux-s0', 'mcu-shang-chi-et-la-legende-des-dix-anneaux', 0, null, null, null, true, null, null),
  ('mcu-spider-man-no-way-home-s0', 'mcu-spider-man-no-way-home', 0, null, null, 148, false, 97, 9),
  ('mcu-doctor-strange-multiverse-of-madness-s0', 'mcu-doctor-strange-multiverse-of-madness', 0, null, null, 126, false, 87, 10),
  ('mcu-thor-love-and-thunder-s0', 'mcu-thor-love-and-thunder', 0, null, null, null, true, null, null),
  ('mcu-black-panther-wakanda-forever-s0', 'mcu-black-panther-wakanda-forever', 0, null, null, null, true, null, null),
  ('mcu-secret-invasion-s1', 'mcu-secret-invasion', 1, null, null, null, true, null, null),
  ('mcu-ant-man-et-la-guepe-quantumania-s0', 'mcu-ant-man-et-la-guepe-quantumania', 0, null, null, null, true, null, null),
  ('mcu-les-gardiens-de-la-galaxie-vol-3-s0', 'mcu-les-gardiens-de-la-galaxie-vol-3', 0, null, null, null, true, null, null),
  ('mcu-the-marvels-s0', 'mcu-the-marvels', 0, null, null, null, true, null, null),
  ('mcu-echo-s1', 'mcu-echo', 1, null, null, null, true, null, null),
  ('fox-x-men-97-s1', 'fox-x-men-97', 1, null, null, null, true, null, null),
  ('mcu-agatha-all-along-s1', 'mcu-agatha-all-along', 1, null, null, null, true, null, null),
  ('mcu-your-friendly-neighborhood-spider-man-s1', 'mcu-your-friendly-neighborhood-spider-man', 1, null, null, null, true, null, null),
  ('fox-deadpool-wolverine-s0', 'fox-deadpool-wolverine', 0, null, null, 128, false, 89, 12),
  ('tv-daredevil-born-again-s1', 'tv-daredevil-born-again', 1, null, null, null, true, null, null),
  ('tv-daredevil-born-again-s2', 'tv-daredevil-born-again', 2, null, null, null, true, null, null),
  ('mcu-ironheart-s1', 'mcu-ironheart', 1, null, null, null, true, null, null),
  ('mcu-marvel-zombies-s1', 'mcu-marvel-zombies', 1, null, null, null, true, null, null),
  ('mcu-captain-america-brave-new-world-s0', 'mcu-captain-america-brave-new-world', 0, null, null, null, true, null, null),
  ('mcu-thunderbolts-s0', 'mcu-thunderbolts', 0, null, null, 127, false, 91, 13),
  ('f4-les-4-fantastiques-premiers-pas-s0', 'f4-les-4-fantastiques-premiers-pas', 0, null, null, 115, true, 95, 14),
  ('mcu-eyes-of-wakanda-s1', 'mcu-eyes-of-wakanda', 1, null, null, null, true, null, null),
  ('mcu-wonder-man-s1', 'mcu-wonder-man', 1, null, null, null, true, null, null),
  ('mcu-visionquest-s1', 'mcu-visionquest', 1, null, null, null, true, null, null),
  ('mcu-spider-man-brand-new-day-s0', 'mcu-spider-man-brand-new-day', 0, null, null, 120, true, 93, 15),
  ('mcu-avengers-doomsday-s0', 'mcu-avengers-doomsday', 0, null, null, null, true, null, null),
  ('tv-daredevil-s1', 'tv-daredevil', 1, null, null, null, true, null, null),
  ('tv-daredevil-s2', 'tv-daredevil', 2, null, null, null, true, null, null),
  ('tv-daredevil-s3', 'tv-daredevil', 3, null, null, null, true, null, null),
  ('tv-jessica-jones-s1', 'tv-jessica-jones', 1, null, null, null, true, null, null),
  ('tv-jessica-jones-s2', 'tv-jessica-jones', 2, null, null, null, true, null, null),
  ('tv-jessica-jones-s3', 'tv-jessica-jones', 3, null, null, null, true, null, null),
  ('tv-luke-cage-s1', 'tv-luke-cage', 1, null, null, null, true, null, null),
  ('tv-luke-cage-s2', 'tv-luke-cage', 2, null, null, null, true, null, null),
  ('tv-iron-fist-s1', 'tv-iron-fist', 1, null, null, null, true, null, null),
  ('tv-iron-fist-s2', 'tv-iron-fist', 2, null, null, null, true, null, null),
  ('tv-the-defenders-s1', 'tv-the-defenders', 1, null, null, null, true, null, null),
  ('tv-the-punisher-s1', 'tv-the-punisher', 1, null, null, null, true, null, null),
  ('tv-the-punisher-s2', 'tv-the-punisher', 2, null, null, null, true, null, null),
  ('tv-agents-of-s-h-i-e-l-d-s1', 'tv-agents-of-s-h-i-e-l-d', 1, null, null, null, true, null, null),
  ('tv-agents-of-s-h-i-e-l-d-s2', 'tv-agents-of-s-h-i-e-l-d', 2, null, null, null, true, null, null),
  ('tv-agents-of-s-h-i-e-l-d-s3', 'tv-agents-of-s-h-i-e-l-d', 3, null, null, null, true, null, null),
  ('tv-agents-of-s-h-i-e-l-d-s4', 'tv-agents-of-s-h-i-e-l-d', 4, null, null, null, true, null, null),
  ('tv-agents-of-s-h-i-e-l-d-s5', 'tv-agents-of-s-h-i-e-l-d', 5, null, null, null, true, null, null),
  ('tv-agents-of-s-h-i-e-l-d-s6', 'tv-agents-of-s-h-i-e-l-d', 6, null, null, null, true, null, null),
  ('tv-agents-of-s-h-i-e-l-d-s7', 'tv-agents-of-s-h-i-e-l-d', 7, null, null, null, true, null, null),
  ('tv-inhumans-s1', 'tv-inhumans', 1, null, null, null, true, null, null),
  ('tv-runaways-s1', 'tv-runaways', 1, null, null, null, true, null, null),
  ('tv-runaways-s2', 'tv-runaways', 2, null, null, null, true, null, null),
  ('tv-runaways-s3', 'tv-runaways', 3, null, null, null, true, null, null),
  ('tv-cloak-dagger-s1', 'tv-cloak-dagger', 1, null, null, null, true, null, null),
  ('tv-cloak-dagger-s2', 'tv-cloak-dagger', 2, null, null, null, true, null, null),
  ('tv-helstrom-s1', 'tv-helstrom', 1, null, null, null, true, null, null),
  ('mcu-the-consultant-s0', 'mcu-the-consultant', 0, null, null, null, true, null, null),
  ('mcu-a-funny-thing-happened-on-the-way-to-thor-s--s0', 'mcu-a-funny-thing-happened-on-the-way-to-thor-s-', 0, null, null, null, true, null, null),
  ('mcu-item-47-s0', 'mcu-item-47', 0, null, null, null, true, null, null),
  ('tv-agent-carter-one-shot-s0', 'tv-agent-carter-one-shot', 0, null, null, null, true, null, null),
  ('mcu-all-hail-the-king-s0', 'mcu-all-hail-the-king', 0, null, null, null, true, null, null),
  ('fox-x-men-s0', 'fox-x-men', 0, null, null, null, true, null, null),
  ('fox-x-men-2-s0', 'fox-x-men-2', 0, null, null, null, true, null, null),
  ('fox-x-men-l-affrontement-final-s0', 'fox-x-men-l-affrontement-final', 0, null, null, null, true, null, null),
  ('fox-x-men-days-of-future-past-s0', 'fox-x-men-days-of-future-past', 0, null, null, null, true, null, null),
  ('fox-logan-s0', 'fox-logan', 0, null, null, null, true, null, null),
  ('fox-deadpool-s0', 'fox-deadpool', 0, null, null, null, true, null, null),
  ('fox-deadpool-2-s0', 'fox-deadpool-2', 0, null, null, null, true, null, null),
  ('fox-x-men-le-commencement-s0', 'fox-x-men-le-commencement', 0, null, null, null, true, null, null),
  ('fox-x-men-apocalypse-s0', 'fox-x-men-apocalypse', 0, null, null, null, true, null, null),
  ('fox-dark-phoenix-s0', 'fox-dark-phoenix', 0, null, null, null, true, null, null),
  ('fox-wolverine-le-combat-de-l-immortel-s0', 'fox-wolverine-le-combat-de-l-immortel', 0, null, null, null, true, null, null),
  ('fox-x-men-origins-wolverine-s0', 'fox-x-men-origins-wolverine', 0, null, null, null, true, null, null),
  ('raimi-spider-man-s0', 'raimi-spider-man', 0, null, null, null, true, null, null),
  ('raimi-spider-man-2-s0', 'raimi-spider-man-2', 0, null, null, null, true, null, null),
  ('raimi-spider-man-3-s0', 'raimi-spider-man-3', 0, null, null, null, true, null, null),
  ('webb-the-amazing-spider-man-s0', 'webb-the-amazing-spider-man', 0, null, null, null, true, null, null),
  ('webb-the-amazing-spider-man-2-s0', 'webb-the-amazing-spider-man-2', 0, null, null, null, true, null, null);
